version: 0.0
env: 
  parameter-store:
    BOT_TOKEN: "/jr/bot_token"
    CLIENT_ID: "/jr/client_id"
    SERVER_ID: "/jr/server_id"
os: linux
files:
  - source: /
    destination: /8sbot
hooks:
  BeforeInstall:
  - location: configure.sh
    timeout: 300
    runas: root
  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
