version: 0.0
os: linux
files:
  - source: /
    destination: /8sbot
hooks:
  BeforeInstall:
  - location: install_dependencies.sh
  timeout: 300
  runas: root
  ApplicationStart:
    - location: index.js
      timeout: 300
      runas: root
